apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
            - name: hello-world-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
      - name: hello-world-conf
        configMap:
          name: hello-world-conf
          items:
            - key: nginx.conf
              path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    app: hello-world
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
  selector:
    app: hello-world
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-conf
  labels:
    app: hello-world
data:
  nginx.conf: |
    events {
    }
    http {
      server {
          listen 8080;
          location / {
              return 200 "Hello, world!";
          }
      }
    }